Menssagens-do-sistema:
  sem-permissao: '&cVocê não tem Permissão!' #Msg de sem permissao geral de todos os comandos desse plugin
  menssagen-cooldown: '&cEspere %cd% segundos para utilizar este comando denovo!' #Quando um comando com cooldown e usado
  warp-nao-existe: '&cA warp ''%warp%'' não existe! Abrindo lista..'
  warp-teleport-msg: '&eVocê foi teleportado para a %warp%'
  menu-warp-ao-abrir: '&eA lista de warps foi aberta!'
  sethome-maximo-homes: '&eVocê bateu o Limite de homes!'
  sethome-sem-argumentos: '&cVocê precisa dizer o nome da sua Home! Exemplo: /sethome casa1'
  sethome-home-ja-existe: '&cEssa home já existe! Delete-a e crie novamente caso queira mudar de lugar'
  sethome-home-criada: "&eHome '%home%' criada com sucesso!"
  sethome-home-criada-erro: "&cUm nome não permitido foi colocado!"
  listhome-mostrando-lista: '&eAbaixo estão todas as suas Homes:'
  listhome-sem-homes: '&cVocê ainda não marcou nenhuma Home!'
  delhome-sem-homes: '&cVocê não tem nenhuma home para excluir!'
  delhome-sucesso: "&eA Home '%home%' foi excluida com sucesso!"
  delhome-erro: '&cErro ao deletar a sua Home!'
  delhome-home-nao-existe: "&ca Home '%home%' não existe!"
  home-teleporte-msg: "&eVocê será teleportado para sua home em %cd% segundos"
  home-nao-existe: "&cA Home '%home%' não existe!"
  home-argumento-errado: "&cUso correto: /home <nome>"
  home-teleporte-sucesso: "&eVocê foi teleportado para a home '%home%'!"
  proibido-marcar-home: "&cVocê não pode marcar Home neste Mundo!"
  maximo-de-spawners: "&cEssa Regiao já esta com o Máximo de Spawners!"
  kit-nao-existe: "&cEste Kit '%kit_display%' não existe! verifique os kits no /menu!"
  kit-em-cooldown: "&cEspere &4%cooldown% &cpara pegar este kit novamente!"
  kit-pego: "&eVocê pegou o kit %kit_display% com sucesso!"
  kit-sobre-peso: "&b%item% &9Caiu no chão! &7(Seu inventário está cheio)"
  kit-sem-perm: "&cVocê não tem permissão para usar este kit!" # Depois daqui nao esta traduzido
  inventario-cheio: "&cSeu Inventario esta Cheio!"
  menu-kits-aberto: "&eMenu de kits foi Aberto!"
  verkit-sem-argumento: "&cVoce precisa especificar o kit que voce quer ver!"
  verkit-kit-nao-existe: "&cEste kit nao existe!"

Boas-vindas:
  title: "&9KingDomRo"
  sub-title: "&7Seja bem-vindo!"

Comandos-config:
  cooldown-global: 5
  max-homes: 5 #NAO RECOMENDAVEL AUMENTAR ISSO PARA COMPATIBILIDADE FUTURA COM AS GUIS
  home-delay: 3
  home-vipdelay: 1


Npcs: #Coloque o nome do npc (tem que colocar os simbolos de cores tambem!)
  warp-npc: '§4§lViajante'

Warps-configs: # SERVE PARA TODAS AS WARPS
  sem-perm-warp: '&cApenas vips podem usar o /warps! procure os Npcs de viagem rápida'
  delay-msg: "&eVocê será teleportado em %delay% segundo's"  #msg do delay do teleport
  warp-sem-perm: "&cVocê não pode ir nesta Warp!"
  cooldown: 5 #/warp cooldown de comando
  delay: 3  #delay para ir ate o warp
  vip-delay: 1 #delay do vip para ir ate a warp
Menu-configs:
  abrir: "&eO Menu foi Aberto!"
  delay-msg: "&eO Menu será aberto nos próximos %delay% segundos!"
  delay: 3 # VIP NAO TEM DELAY!
  cooldown: 5 #/menu cooldown

Kits-menu:
  pegar-kit: "&aPegar Kit"
  cancelar-kit: "&cCancelar"
  sectionkit-voltar: "&eVoltar"
  menuStyle1-exit: "&cIr para o Menu Principal"
  sem-cooldown: "&aVocê pode Pegar!"
  com-cooldown: "&fFaltam: &c%cd%"
  com-perm: "&aVocê tem permissão para pegar. "
  sem-perm: "&cVocê não tem permissão para pegar. "
  kits-menu-title: "             &9Menu de Kits"
  kit-membro: "&f      - ✦ &aKits Membros &f✦ -      "
  kit-membro-lore:
    - ""
    - " &8* &7Aqui você pode coletar Kits &aBasicos "
    - " &8* &7Para Iniciar no mundo da &aSobrevivência&7 "
    - ""
  kit-vip1: "&f      - ✦ &bKits Vips &f✦ -      "
  kit-vip1-lore:
    - ""
    - " &8* &7Aqui você pode coletar Kits &bVips "
    - " &8* &7Para Auxiliar no mundo de &aSobrevivência &7e &cPvP "
    - ""
  kit-vip2: "&f      - ✦ &cKits &fYou&ctubers &f✦ -      "
  kit-vip2-lore:
    - ""
    - " &8* &7Aqui você pode coletar Kits &fYou&ctubers "
    - " &8* &7Para Auxiliar na &3Criação de conteúdo "
    - ""
  kit-vip3: "&f      - ✦ &5Kits Especiais &f✦ -      "
  kit-vip3-lore:
    - ""
    - " &8* &7Aqui você pode coletar Kits &5Especiais "
    - " &8* &7Para Comemorar &5Eventos do Servidor "
    - ""

Configs-Spawn:
  spawn-title-msg: '&9&lSpawn' #title de quando e teleportado para o spawn
  spawn-subtitle-msg: '&7Bem-vindo ao spawn' #subtitle de quando e teleportado para o spawn
  spawn-delay-msg: "&eVocê ira para o Spawn em %delay% segundo's!" #/spawn delay msg
  cooldown: 5 #/spawn cooldown de comando
  delay: 3 #delay para ir ate o spawn
  vip-delay: 1 #delay do vip para ir ate o spawn

Gui-config: #PODE SER ADICIONADO QUANTAS LORES VOCE QUERER!
  listhomes:
    homes_lores:
      - ''
      - "&8&l * &fAo clicar você será teletransportado"
      - "&8&l * &fPara a sua home '&e&l%home%&f'"
      - ''
  menu:
    player_nome: "&9&l%player%"
    player_lore:
      - "&fbanco: &2%banco%"
      - "&fgrupo: &2%grupo%"
    lobby_nome: "lobbyvip"
    lobby_lore:
      - "test"
      - "test2"
    sethome_nome: "sethome"
    sethome_lore:
      - "test"
      - "test2"
    clan_nome: "clan"
    clan_lore:
      - "test"
      - "test2"
    jobs_nome: "jobs"
    jobs_lore:
      - "test"
      - "test2"
    pets_nome: "pets"
    pets_lore:
      - "test"
      - "test2"
    enderchest_nome: "enderchest"
    enderchest_lore:
      - "test"
      - "test2"
    kits_nome: "kits"
    kits_lore:
      - "test"
      - "test2"
    backpack_nome: "backpack"
    backpack_lore:
      - "test"
      - "test2"
    warpvips_nome: "warpvips"
    warpvips_lore:
      - "test"
      - "test2"
    shopvip_nome: "shopvip"
    shopvip_lore:
      - "test"
      - "test2"
  warp:
    end-name: "&e   - -=- ✪ - &e&lEnd &e- ✪ -=- -"
    end-lore:
      - ""
      - "&7  Essa opção te levará para   "
      - "&7  O mundo do &5Ender Dragon&7.  "
      - ""
      - "&c  PvP: &2✔                 "
      - ""
    lobby-name: "&e   - -=- ✪ - &e&lLobby &e- ✪ -=- -  "
    lobby-lore:
      - ""
      - "&7  Essa opção te levará para   "
      - "&7  O mundo do &9Spawn&7.  "
      - ""
      - "&c  PvP: &2✘                 "
      - ""
    minerar-name: "&e   - -=- ✪ - &e&lMinerar &e- ✪ -=- -  "
    minerar-lore:
      - ""
      - "&7  Essa opção te levará para   "
      - "&7  O mundo de &3Minerar&7.  "
      - ""
      - "&c  PvP: &2✔"
      - ""
    nether-name: "&e   - -=- ✪ - &e&lNether &e- ✪ -=- -  "
    nether-lore:
      - ""
      - "&7  Essa opção te levará para   "
      - "&7  O mundo do &cNether&7.  "
      - ""
      - "&c  PvP: &2✔"
      - ""
    bricks-name: "&e   - -=- ✪ - &e&lSurvival &e- ✪ -=- -  "
    bricks-lore:
      - ""
      - "&7  Essa opção te levará para   "
      - "&7  O mundo do &2Survival&7.  "
      - ""
      - "&c  PvP: &2Apenas a Noite!"
      - ""
    arena-name: "&e   - -=- ✪ - &e&lArena &e- ✪ -=- -  "
    arena-lore:
      - ""
      - "&7  Essa opção te levará para   "
      - "&7  O mundo da &4Arena&7.  "
      - ""
      - "&c  PvP: &2✔"
      - ""
    eventos-name: "&e   - -=- ✪ - &e&lEventos &e- ✪ -=- -  "
    eventos-lore:
      - ""
      - "&7  Essa opção te levará para   "
      - "&7  O mundo da &5Eventos&7.  "
      - ""
      - "&c  PvP: &2✘                 "
      - ""
